# Generated by Django 6.1.1 on 2026-10-01 08:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('type', models.CharField(choices=[('C', 'Corrente'), ('P', 'Poupança'), ('W', 'Carteira'), ('I', 'Investimento')], default='C', max_length=1, verbose_name='tipo')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='saldo inicial')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='users.workspace', verbose_name='espaço')),
            ],
            options={
                'verbose_name': 'conta',
                'verbose_name_plural': 'contas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('type', models.CharField(choices=[('R', 'Receita'), ('D', 'Despesa')], max_length=1, verbose_name='tipo')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='users.workspace', verbose_name='espaço')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), 'O valor deve ser maior que zero.')], verbose_name='valor limite')),
                ('reference_month', models.DateField(verbose_name='mês de referência')),
                ('alert_sent', models.BooleanField(default=False, verbose_name='alerta enviado')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='users.workspace', verbose_name='espaço')),
                ('category', models.ForeignKey(limit_choices_to={'type': 'D'}, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='finances.category', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'orçamento',
                'verbose_name_plural': 'orçamentos',
                'ordering': ['-reference_month'],
            },
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('limit', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), 'O valor deve ser maior que zero.')], verbose_name='limite')),
                ('closing_day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'O dia deve estar entre 1 e 31.'), django.core.validators.MaxValueValidator(31, 'O dia deve estar entre 1 e 31.')], verbose_name='dia de fechamento')),
                ('due_day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'O dia deve estar entre 1 e 31.'), django.core.validators.MaxValueValidator(31, 'O dia deve estar entre 1 e 31.')], verbose_name='dia de vencimento')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to='finances.account', verbose_name='conta')),
            ],
            options={
                'verbose_name': 'cartão de crédito',
                'verbose_name_plural': 'cartões de crédito',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), 'O valor deve ser maior que zero.')], verbose_name='valor alvo')),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'), 'O valor não pode ser negativo.')], verbose_name='valor atual')),
                ('deadline', models.DateField(verbose_name='prazo')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='users.workspace', verbose_name='espaço')),
            ],
            options={
                'verbose_name': 'meta financeira',
                'verbose_name_plural': 'metas financeiras',
                'ordering': ['deadline'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_month', models.DateField(verbose_name='mês de referência')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'), 'O valor não pode ser negativo.')], verbose_name='valor total')),
                ('status', models.CharField(choices=[('A', 'Aberta'), ('F', 'Fechada'), ('P', 'Paga')], default='A', max_length=1, verbose_name='status')),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='finances.creditcard', verbose_name='cartão de crédito')),
            ],
            options={
                'verbose_name': 'fatura',
                'verbose_name_plural': 'faturas',
                'ordering': ['-reference_month'],
            },
        ),
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='descrição')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), 'O valor deve ser maior que zero.')], verbose_name='valor')),
                ('type', models.CharField(choices=[('R', 'Receita'), ('D', 'Despesa')], max_length=1, verbose_name='tipo')),
                ('due_day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'O dia deve estar entre 1 e 31.'), django.core.validators.MaxValueValidator(31, 'O dia deve estar entre 1 e 31.')], verbose_name='dia de vencimento')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='lembrete enviado')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transactions', to='finances.account', verbose_name='conta')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_transactions', to='finances.category', verbose_name='categoria')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transactions', to='users.workspace', verbose_name='espaço')),
            ],
            options={
                'verbose_name': 'transação recorrente',
                'verbose_name_plural': 'transações recorrentes',
                'ordering': ['due_day'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='descrição')),
                ('type', models.CharField(choices=[('R', 'Receita'), ('D', 'Despesa')], max_length=1, verbose_name='tipo')),
                ('date', models.DateField(verbose_name='data')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), 'O valor deve ser maior que zero.')], verbose_name='valor')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finances.account', verbose_name='conta')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finances.category', verbose_name='categoria')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='users.profile', verbose_name='responsável')),
            ],
            options={
                'verbose_name': 'transação',
                'verbose_name_plural': 'transações',
                'ordering': ['-date'],
            },
        ),
    ]
